
DEBUG = False
TESTING = False
CSRF_ENABLED = True
JWT_ACCESS_TOKEN_EXPIRES = False
# JWT_REFRESH_TOKEN_EXPIRES = False
SECRET_KEY = '98930a22418'
PROPAGATE_EXCEPTIONS = True
SQLALCHEMY_POOL_SIZE=100
SQLALCHEMY_POOL_TIMEOUT=180
SQLALCHEMY_POOL_RECYCLE=180
SQLALCHEMY_DATABASE_URI = 'mysql://root:98930a22418@localhost/onlineexam'
#UPLOAD_FOLDER = '/home/pravin/upload'
SQLALCHEMY_TRACK_MODIFICATIONS = False
MAIL_SERVER='smtp.easyonlineexam.com'
MAIL_PORT = 587
MAIL_USERNAME = 'info@easyonlineexam.com'
MAIL_PASSWORD = 'c$#Hfmo0'
MAIL_USE_TLS = True
MAIL_USE_SSL = False

